# Generated by Django 3.0.2 on 2021-02-09 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tblservicelog',
            name='time',
        ),
        migrations.AddField(
            model_name='tblservicelog',
            name='occurrences',
            field=models.IntegerField(default=0),
        ),
    ]
